name: QA
on:
  pull_request:
    paths:
      - '**.cs'
      - '**.csproj'
  push:
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  inspection:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'
        - name: Restore
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore -warnAsError NatureRemoMonitor
        - name: Inspection
          uses: muno92/resharper_inspectcode@v1
          with:
            solutionPath: ./life_log.sln
            minimumSeverity: warning
            ignoreIssueType: NotAccessedPositionalProperty.Global
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Run Nature Remo Test
        run: dotnet test NatureRemoTest
        env:
          NATURE_REMO_ACCESS_TOKEN: ${{ secrets.NATURE_REMO_ACCESS_TOKEN }}
      - name: Run SpreadSheet Test
        run: dotnet test SpreadSheetTest
        env:
          GOOGLE_SHEET_CREDENTIAL: ${{ secrets.GOOGLE_SHEET_CREDENTIAL }}
          TEST_SPREADSHEET_ID: ${{ secrets.TEST_SPREADSHEET_ID }}

