name: QA
on:
  [pull_request, push]
  
jobs:
  inspection:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
        - name: Restore
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore -warnAsError NatureRemoMonitor
        - name: Inspection
          uses: muno92/resharper_inspectcode@1.3.0
          with:
            solutionPath: ./life_log.sln
            version: 2021.3.2
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Restore
        run: dotnet restore
      - name: Run Test
        run: dotnet test NatureRemoTest
        env:
          NATURE_REMO_ACCESS_TOKEN: ${{ secrets.NATURE_REMO_ACCESS_TOKEN }}

