name: Record Sensor Value
on:
#  schedule:
#    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:master
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        NATURE_REMO_ACCESS_TOKEN: ${{ secrets.NATURE_REMO_ACCESS_TOKEN }}
        GOOGLE_SHEET_CREDENTIAL: ${{ secrets.GOOGLE_SHEET_CREDENTIAL }}
        SPREADSHEET_ID_FOR_REMO: ${{ secrets.SPREADSHEET_ID_FOR_REMO }}
    steps:
      - name: Record
        run: cd /app && ./NatureRemoMonitor
